#!/usr/bin/env bash
export DATABASE_URI=postgresql://postgres:postgres@localhost:5433/deeptracy;
export PLUGINS_LOCATION=/Users/sergio.fernandez/PycharmProjects/deeptracy/plugins;
export PYTHONUNBUFFERED=1;
export PATTON_URI=http://localhost:8000;
export SHARED_VOLUME_PATH=/tmp/deeptracy;
export LOCAL_PRIVATE_KEY_FILE=/Users/sergio.fernandez/PycharmProjects/deeptracy/tests/acceptance/private_key/local_id_rsa;
export LOG_LEVEL=DEBUG;
export A=a;
export BROKER_URI=redis://localhost:6379
